### ISSUE TITLE
Sensor documentation

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-docs#30]
Currently we have three places where sensor information is added:

1. [Supported sensors page](https://docs.smartcitizen.me/Components/Auxiliary%20Connector/)
2. [Sensor knowledge](https://docs.smartcitizen.me/Components/sensors/performance/)
3. [Guides for calibrating / using each sensor](https://docs.smartcitizen.me/Guides/calibration/SCD30%20CO2%20sensor/)

For maintainability purposes, it would be great if we can do something similar to what we did in the [mdef-docs](https://mdef.fablabbcn.org/faculty/) for faculty and other content that can be processed by a macro.

**Current proposal:**

- [ ] We move sensors performance/knowledge toc item to a nav item
- [ ] We organise by:
``` 
- Sensors: brief explanation. Onboard and external. 
    - Air: brief explanation, supporting documents. Supported sensors summary with colors to distinguish onboard vs external.
        - CO2:  explanation of the metric, plus supported sensor cards (summary page)
            - Sensor 1,
            - Sensor 2...
        - PM:  explanation of the metric, plus supported sensor cards (summary page)
            - Sensor 1,
            - Sensor 2...
    - Water: brief explanation, supporting documents. Supported sensors summary with colors to distinguish onboard vs external.
        - pH: explanation of the metric, plus supported sensor cards (summary page)
            - Sensor 1,
            - Sensor 2...
```

An **example** is already found on the docs already: /hardware/sensors/air/co2/Sensirion_SCD30/

A **good visual reference** for this can be found on: https://blokas.io

**TODO:**

- [ ] Finalise frontmatter for each sensor @oscgonfer 
- [ ] Adapt all sensors to same frontmatter schema @oscgonfer @peters-rebecca 
- [ ] Work on the card design @peters-rebecca 
- [ ] Add card views on each summary page @peters-rebecca 
- [ ] Add descriptions to each level (main, field, metric) @oscgonfer @peters-rebecca 
- [ ] Make sure images work @peters-rebecca
